### ISSUE TITLE
Farmer using lots of RAM

### ISSUE THREAD

**Issue by jim-counter** [subspace/pulsar#238]
There have been a number of reports within the community that the farmer is using lots of RAM.

<details>

![image](https://github.com/subspace/subspace/assets/11335994/fe1a2be0-5c82-4fbe-ba41-b544db560832)

![image](https://github.com/subspace/subspace/assets/11335994/e47bafaf-e096-459e-a00a-fcbfa69d9064)

![image](https://github.com/subspace/subspace/assets/11335994/f2879dc3-4603-4d26-a032-80bfedfc3bf5)

</details>

Discord conversations:

https://discord.com/channels/864285291518361610/1125601137974857728
https://discord.com/channels/864285291518361610/1125506173404192838

Possible related issue: [Farmer crashing due to excessive memory usage subspace/subspace#1606](https://github.com/subspace/subspace/issues/1606).

**Comment by tysjiang** [comment]
using the august 31 binaries to plot, seeing memory increase roughly 1GB every 2 minutes

tested on windows 11 with 48gigs of ram

node command used:
.\subspace-node-windows-x86_64-skylake-gemini-3f-2023-aug-31.exe `
--chain gemini-3f `
--execution wasm `
--blocks-pruning 256 `
--state-pruning archive `
--no-private-ipv4 `
--validator `
--name "XXX"

farmer command used:
.\subspace-farmer-windows-x86_64-skylake-gemini-3f-2023-aug-31.exe farm --reward-address XXX `
path=C:\subspace\farm,size=100G `
path=C:\subspace\farm1,size=1T `

note: memory increase a lot faster if plot is bigger than 1T and if there are more than a few plots

**Comment by jim-counter** [comment]
Hi @tysjiang! Thanks for the report. Could you move this issue over to our [monorepo](https://github.com/subspace/subspace/issues) please? This one is specifically for Pulsar which is a different way of running a node and farmer.

**Comment by nazar-pc** [comment]
I think we have established that neither Pulsar nor reference implementation actually use a lot of RAM. It is Windows that reports memory usage in a strange way, if you actually look at how much memory does the process use it is not a lot at all. And you open other apps you'll notice they don't crash with "out of memory" error, meaning memory is available for use, Windows just doesn't report it as such.

I'm closing this as non-issue for now.
